from app.schemas.domain import Material

SEED_MATERIALS: list[Material] = [
    Material(
        id="mat-ldsp-white-16",
        code="LDSP-WHITE-16",
        name="ЛДСП Белый 16мм",
        color="#ffffff",
        textureUrl="/static/textures/ldsp_white_16.jpg",
        thicknessMmDefault=16,
        grainDirection="none",
        category="laminate",
    ),
    Material(
        id="mat-ldsp-grey-16",
        code="LDSP-GREY-16",
        name="ЛДСП Серый 16мм",
        color="#b0b0b0",
        textureUrl="/static/textures/ldsp_grey_16.jpg",
        thicknessMmDefault=16,
        grainDirection="none",
        category="laminate",
    ),
    Material(
        id="mat-ldsp-oak-light-16",
        code="LDSP-OAK-LIGHT-16",
        name="ЛДСП Дуб светлый 16мм",
        color="#c8a96e",
        textureUrl="/static/textures/ldsp_oak_light_16.jpg",
        thicknessMmDefault=16,
        grainDirection="lengthwise",
        category="laminate",
    ),
    Material(
        id="mat-ldsp-oak-dark-16",
        code="LDSP-OAK-DARK-16",
        name="ЛДСП Дуб тёмный 16мм",
        color="#6b4226",
        textureUrl="/static/textures/ldsp_oak_dark_16.jpg",
        thicknessMmDefault=16,
        grainDirection="lengthwise",
        category="laminate",
    ),
    Material(
        id="mat-mdf-white-18",
        code="MDF-WHITE-18",
        name="МДФ Белый 18мм",
        color="#f5f5f5",
        textureUrl="/static/textures/mdf_white_18.jpg",
        thicknessMmDefault=18,
        grainDirection="none",
        category="mdf",
    ),
    Material(
        id="mat-mdf-white-16",
        code="MDF-WHITE-16",
        name="МДФ Белый 16мм",
        color="#f5f5f5",
        textureUrl="/static/textures/mdf_white_16.jpg",
        thicknessMmDefault=16,
        grainDirection="none",
        category="mdf",
    ),
    Material(
        id="mat-countertop-oak-38",
        code="CTOP-OAK-38",
        name="Столешница Дуб 38мм",
        color="#b8935a",
        textureUrl="/static/textures/ctop_oak_38.jpg",
        thicknessMmDefault=38,
        grainDirection="lengthwise",
        category="countertop",
    ),
    Material(
        id="mat-dvp-white-3",
        code="DVP-WHITE-3",
        name="ДВП Белый 3мм",
        color="#fafafa",
        textureUrl="/static/textures/dvp_white_3.jpg",
        thicknessMmDefault=3,
        grainDirection="none",
        category="hardboard",
    ),
]
